openapi: 3.0.3
info:
  title: Image Processing API
  description: API for uploading, converting, listing, downloading, and searching images using AWS S3.
  version: 1.0.0
servers:
  - url: /api/images

paths:
  /upload:
    post:
      summary: Upload an image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  fileUrl:
                    type: string
                  fileKey:
                    type: string
                  presigned_url:
                    type: string

  /convert/{filename}:
    post:
      summary: Convert image with optional resizing and upload to S3
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
        - in: query
          name: width
          required: false
          schema:
            type: integer
            minimum: 1
        - in: query
          name: height
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Image converted and uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  fileKey:
                    type: string
                  presigned_url:
                    type: string

  /:
    get:
      summary: List all uploaded images
      responses:
        '200':
          description: List of uploaded images
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        presigned_url:
                          type: string

  /download/original/{filename}:
    get:
      summary: Download the original uploaded image
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Original image file (binary)
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /download/converted/{filename}:
    get:
      summary: Download a converted image
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Converted image file (binary)
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /search:
    get:
      summary: Search uploaded images by name
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 6
      responses:
        '200':
          description: Paginated image search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  pageSize:
                    type: integer
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                        presigned_url:
                          type: string

  /test:
    get:
      summary: Test endpoint to check if API is running
      responses:
        '200':
          description: Test successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
